version: '3.7'

services:
  parcel:
    volumes:
      - static:/app/bundles
    build:
     context: .
     dockerfile: Dockerfile_Parcel

  django_gunicorn:
    volumes:
      - static:/static
      - static:/app/bundles
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_Django
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8179:8179"
    depends_on:
      - django_gunicorn

volumes:
  static:


