version: '3.7'

services:
  parcel:
    volumes:
      - static:/app/bundles
    build:
     context: .
     dockerfile: Dockerfile_Parcel
    command: >
        bash -c "npm ci --dev
        && ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url='./' "

  django_gunicorn:
    volumes:
      - static:/static
      - static:/app/bundles
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_Django
    command: >
        bash -c "python manage.py collectstatic --no-input
        && gunicorn star_burger.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - parcel

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8179:8179"
    depends_on:
      - django_gunicorn

volumes:
  static:


