# Generated by Django 3.2.15 on 2023-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230107_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set(),
        ),
    ]
