# Generated by Django 3.2.15 on 2023-01-09 21:18

from django.db import migrations


def add_price_to_orderdetail_model(apps, shema_editor):
    OrderDetail = apps.get_model('foodcartapp', 'OrderDetail')
    for items in OrderDetail.objects.iterator():
        items.price = items.amount * items.product.price
        items.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderdetail_price'),
    ]

    operations = [
        migrations.RunPython(add_price_to_orderdetail_model)
    ]
