# Generated by Django 3.2.15 on 2023-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230109_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Необработанный'), ('CLOSED', 'Закрыт')], default='OPEN', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
