# Generated by Django 3.2.15 on 2023-01-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличными')], db_index=True, default='CASH', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
