# Generated by Django 3.2.15 on 2023-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230131_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличными')], db_index=True, default='Не выбрано', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
