# Generated by Django 3.2.15 on 2023-01-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличными')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
