# Generated by Django 3.2.15 on 2023-02-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20230202_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='price',
            new_name='position_price',
        ),
    ]
