# Generated by Django 3.2.15 on 2023-01-24 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('updated', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 1, 24, 21, 9, 40, 135933, tzinfo=utc))),
            ],
            options={
                'verbose_name': ('Место',),
                'verbose_name_plural': 'Места',
            },
        ),
    ]
