# Generated by Django 3.2.15 on 2023-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
