# Generated by Django 3.2.15 on 2023-02-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ya_geocoder', '0002_auto_20230131_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
